### PR TITLE
Jwt client

### PR DESCRIPTION
**Pull request by QueensCoder**
Implemented JWT authentication login. A user is able to ask django server for JWT, upon successful response user gets token and is now able to request toy data from server.

Installed universal cookie in order to have react store the JWT tokens both access and refresh on a clients cookies.

### CODE REVIEW

**Review by swarna-rgb — COMMENTED** [review]
Ok looks good

**Review by swarna-rgb — CHANGES_REQUESTED** [review]
store your token in memory

**Review by QueensCoder — COMMENTED** [review]
Fixed localStorage vs cookies issue now using localStorage

**Comment by QueensCoder** [comment]
Fixed the issue using memory instead of cookies

**Comment by QueensCoder** [comment]
Ready to merge

**Comment by swarna-rgb** [comment]
Ok merged

**Pull request merged**
